{
  # Generated by ‘nixos-generate-config’. Contributes to the same
  # `flake.modules.nixos.spider` attribute as ../spider.nix; the two
  # definitions merge.
  flake.modules.nixos.spider =
    {
      config,
      lib,
      modulesPath,
      ...
    }:
    {
      imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "sdhci_pci"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-c4a60096-b378-4870-8bad-829ab3837852";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-c4a60096-b378-4870-8bad-829ab3837852".device =
        "/dev/disk/by-uuid/c4a60096-b378-4870-8bad-829ab3837852";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/ED20-8529";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        {
          device = "/swapfile";
          size = 8 * 1024;
        }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
