# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-75036819-4d49-4d28-9725-3e819e4f64ae";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-75036819-4d49-4d28-9725-3e819e4f64ae".device = "/dev/disk/by-uuid/75036819-4d49-4d28-9725-3e819e4f64ae";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7B1E-F564";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-d16f06b6-ac85-4ed5-b721-c2667b5c8e4a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d16f06b6-ac85-4ed5-b721-c2667b5c8e4a".device = "/dev/disk/by-uuid/d16f06b6-ac85-4ed5-b721-c2667b5c8e4a";

  fileSystems."/mnt/data" =
    { device = "/dev/mapper/luks-caaf6bd5-d8af-475d-b12a-d2ef153fdf39";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-caaf6bd5-d8af-475d-b12a-d2ef153fdf39".device = "/dev/disk/by-uuid/caaf6bd5-d8af-475d-b12a-d2ef153fdf39";

  swapDevices =
    [ { device = "/dev/mapper/luks-63c8a216-3ef1-4cb5-b977-102856cec5ca"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
